export { default as Mission } from './Mission'
export { default as Stats } from './Stats'
export { default as WhatWeDo } from './WhatWeDo'
export { default as OurValues } from './OurValues'
export { default as WhatPeopleSay } from './WhatPeopleSay'
export { default as OurTeam } from './OurTeam'